### ISSUE TITLE
안녕하세요~

### ISSUE THREAD

**Issue by leeyunhome** [moonyl/yuv-player#1]
안녕하세요~

혹시 yuv-player

빌드방법좀 설명해주실 수 있나요?

감사합니다. ㅠ

**Comment by moonyl** [comment]
메일 확인이 늦었네요.
2년 전쯤에 재생 성능 개선 방법 검토한다고 잠깐 작성했는데 관심있는 분이 계실지는 몰랐네요.
https://github.com/moonyl/yuv-player  README.md 파일로 간단히 설치 및 빌드 방법을 기록해
뒀습니다.참고하시기 바랍니다.
좋은 하루 지내시길 바랍니다.

2020년 6월 12일 (금) 오후 4:26, leeyunhome <notifications@github.com>님이 작성:

**Comment by leeyunhome** [comment]
감사합니다~. 

메일로도 보내드렸는데 혹시 상용소프트웨어에 본 프로젝트의 소스코드를 사용해도 되는지 여쭤봅니다.

좋은 하루 되세요

**Comment by moonyl** [comment]
제가 작성한 코드도 이미 누군가에게 작성된 예제들을 통해서 재구성을 한 것이므로, 제약을 할 생각은 없습니다. 그러나, 제가 사용한 예제 자체가 제약이 있는지는 모르겠습니다. 아마도 구글링을 통해 찾은 snippet 을 모아서 만들었기 때문에 상용으로 사용하셔도 큰 문제는 되지 않을 것이라 판단합니다.

**Comment by leeyunhome** [comment]
> 제가 작성한 코드도 이미 누군가에게 작성된 예제들을 통해서 재구성을 한 것이므로, 제약을 할 생각은 없습니다. 그러나, 제가 사용한 예제 자체가 제약이 있는지는 모르겠습니다. 아마도 구글링을 통해 찾은 snippet 을 모아서 만들었기 때문에 상용으로 사용하셔도 큰 문제는 되지 않을 것이라 판단합니다.

답변감사합니다~ . 저 star가 많아졌으면 좋겠네요~
